### ISSUE TITLE
JWE "zip" support

### ISSUE THREAD

**Issue by lukaszgieraltowski** [airsidemobile/JOSESwift#107]
Are we going to handle compression?
specs: https://tools.ietf.org/html/rfc7516#section-4.1.3

I'm afraid this would involve the addition of dependency to external library like [DataCompression](https://github.com/mw99/DataCompression).

**Comment by daniel-mohemian** [comment]
Hi @lukaszgieraltowski, 👋 

Sorry for the late reply.

Of course,  it would be cool to support compression. Unfortunately, we currently do not have plans to do it ourselves in the near future. If you have a suggestion on how to implement it, I'd be more than happy to review and merge a pull request! 👍
