### ISSUE TITLE
iOS 9 support

### ISSUE THREAD

**Issue by ashrafulkarim** [airsidemobile/JOSESwift#108]
Hello, 
My target SDK is iOS 9.0, so the pod fails with,

> Specs satisfying the `JOSESwift` dependency were found, but they required a higher minimum deployment target.

Any plan to downgrade the supported iOS?

**Comment by daniel-mohemian** [comment]
Hi @ashrafulkarim,

thanks for checking out JOSESwift. 👍 

we were planning on always supporting the two latest major versions of iOS. Have you tried cloning the library and lowering the deployment target to iOS 9? If it still builds, we might lower it to iOS 9 (after making sure it doesn't cause any problems with open pull requests and planned features).

**Comment by ashrafulkarim** [comment]
No, struct SecKeyAlgorithm, func SecKeyIsAlgorithmSupported, SecKeyCreateSignature, SecKeyVerifySignature etc requires iOS 10. :(

**Comment by daniel-mohemian** [comment]
Ok 😢  These are core functions in our current crypto implementations. We do not plan to replace them with older APIs.

But, feel free to poke around. Maybe it's easy to replace them after all.

Thanks again.
