### ISSUE TITLE
Initialize `JWEHeader` with additional parameters

### ISSUE THREAD

**Issue by fbernutz** [airsidemobile/JOSESwift#109]
At the moment the only way to initialize a `JWEHeader` is with the following syntax, like it is described in the [documentation](https://github.com/airsidemobile/JOSESwift/wiki/jwe#header-1): 

```swift 
 let header = JWEHeader(algorithm: .RSA1_5, encryptionAlgorithm: .A256CBCHS512)
```

It's not quite clear to me why all the parameters (see [here](https://github.com/airsidemobile/JOSESwift/blob/master/JOSESwift/Sources/JWEHeader.swift#L94)) are accessible to read but not to write. The public initializer described above is the only way to initialize the JWE header, so all the parameters have to be always `nil`, right? 

I would be glad, if you could give me a hint, if it's possible to declare an additional parameter like `kid` and how to do it.

**Comment by daniel-mohemian** [comment]
Hi @fbernutz 👋 

You are right, our current header implementation is quite limited. There's no specific reason why the parameters are read-only. It's probably a bug. I'll have a look at your pull request later this week and will then revisit this issue to discuss options on how to properly support more than a few parameters. 😄
