### ISSUE TITLE
Update wiki for keyIdentifier in JWEHeader

### ISSUE THREAD

**Issue by fbernutz** [airsidemobile/JOSESwift#111]
Relates to #110 

In combination with the Pull Request which added the keyIdentifier as argument of JWEHeader initializer, I would like to update the documentation in the [Wiki page for `JWE`](https://github.com/airsidemobile/JOSESwift/wiki/jwe#header). 
After the example of the initialization with the two parameter, I would add another example: 

---

#### Example with key identifier

The following header specifies two algorithms and a key identifier. This results in the following JWE header.

``` swift
{ "alg": "RSA1_5", "enc": "A256CBC-HS512", "kid": "your_keyIdentifier" }
```

To add a key identifier can be necessary when you are working with a decryption instance (like a backend with multiple stages) with multiple keys. With the key identifier the decryption service can find the correct key.

**Comment by daniel-mohemian** [comment]
Good point @fbernutz! I will update the readme and wiki with your changes from #110.

Not sure what the best process for contributing to wikis is. Seems like they don't support pull requests out of the box.  However, [this blog](https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html) suggests a workaround to get pull requests to work. I'll look into that some time. 😄
