### ISSUE TITLE
get nil while create verifier using public key

### ISSUE THREAD

**Issue by shydow** [airsidemobile/JOSESwift#125]
code:

let publicKey = SecKeyCreateWithData(data! as CFData, attributes as CFDictionary, &error)

let jws = try JWS(compactSerialization: serialization)
let verifier = Verifier(verifyingAlgorithm: .RS256, publicKey: publicKey) // get nil while create verifier
let payload = try jws.validate(using: verifier!).payload
let message = String(data: payload.data(), encoding: .utf8)!

**Comment by daniel-mohemian** [comment]
Interesting, I'll take a look. Can you confirm, that `publicKey` is not `nil` in your example?

**Comment by daniel-mohemian** [comment]
I could not reproduce your problem with the latest version of JOSESwift (1.4.0) on Xcode 10.1.

The following code 

``` swift
let publicKey = /* Generate public key */

// Get public key data
guard let publicKeyData = SecKeyCopyExternalRepresentation(publicKey, nil) else {
  print("Could not get data of public key.")
  return
}

let attributes: [String: Any] = [
  kSecAttrKeyType as String: kSecAttrKeyTypeRSA,
  kSecAttrKeyClass as String: kSecAttrKeyClassPublic,
  kSecAttrKeySizeInBits as String: 2048
]

// Create public key from data
guard let publicKeyFromData = SecKeyCreateWithData(publicKeyData, attributes as CFDictionary, nil) else {
  print("Could not create public key from data.")
  return
}

// Construct verifier from imported public key
let verifier = Verifier(verifyingAlgorithm: .RS256, publicKey: publicKeyFromData)

if verifier == nil {
  print("Verifier is nil.")
} else {
  print("Verifier is ok.")
}
```

prints `"Verifier is ok."`. 

I suspect, that your public key was `nil`. Please double check your code. Feel free to open another issue if you still have the problem despite having a fully initialized public key.
