### ISSUE TITLE
ES256 for JWE

### ISSUE THREAD

**Issue by ayechanpyaesonework** [airsidemobile/JOSESwift#162]
Hello, I am wondering when can we have ES256 support for JWE.

**Comment by daniel-mohemian** [comment]
Hi @ayechanpyaesonework 👋 

_ES256_ is an algorithm for digital signatures and MACs as specified in JWA ([RFC-7518, 3.1](https://tools.ietf.org/html/rfc7518#section-3.1)). You can find the algorithms for JWE in the same RFC, sections 4 and 5.
