### ISSUE TITLE
Apache license header missing from some files

### ISSUE THREAD

**Issue by nathan-mohemian** [airsidemobile/JOSESwift#174]
I just noticed that a few source files (at least `JWE/Compressor.swift` and `Common/JOSESwiftError.swift`) are missing license headers.

Not sure how these got overlooked, there may be a few others as well 🤔

**Comment by daniel-mohemian** [comment]
Seems like we weren't as strict with @haeser as we should've been with the compression PR. 😅 I'll update it, thanks for reporting.
