### ISSUE TITLE
 EC Encryption - ECDSA

### ISSUE THREAD

**Issue by VishnuV02** [airsidemobile/JOSESwift#176]
I have to Do EC Encryption ECDSA by JoseSwift library. i Created a key pair using SecKeyCreateRandomKey and generated a shared key by SecKeyCopyKeyExchangeResult. How to do encryption using JWE Encryptor method in JOSESWIFT?

**Comment by VishnuV02** [comment]
Thanks for your reply! Is it possible to give support for ECDH_ES in JOSESWIFT Library?

**Comment by nathan-mohemian** [comment]
We don't have plans to add it ourselves, but would gladly accept any PRs.
