### ISSUE TITLE
EC Encryption with Direct Algorithm

### ISSUE THREAD

**Issue by VishnuV02** [airsidemobile/JOSESwift#177]
I am trying to do EC Encryption with Direct Algorithm.
static func doEC_DIR_Encryption(plainJSONData: String, pKey: String) -> String 
{
    let D = Data(pKey.utf8)
    let jwk = try! ECPublicKey(data: D)
    let secKey: SecKey = try! jwk.converted(to: SecKey.self)

    Following is the seckey from server,
    <SecKeyRef curve type: kSecECCurveSecp256r1, algorithm id: 3, key type: ECPublicKey, 
    version: 4, block size: 256 bits, y: 
    CF757E55EF9C330B79F5060168786BE8714C081682F771F867BA61A9BF3C6415, x: 
    CDDD8A78CDB0A6AEAEA217AB8267217C9BECE5A242F26D53564654F018159B91, addr: 
    0x10351c3b0>

    let encrypter = Encrypter(keyEncryptionAlgorithm: .direct, encryptionKey: secKey, 
    contentEncyptionAlgorithm: .A256CBCHS512)!

     let header = JWEHeader(algorithm: .direct, encryptionAlgorithm: .A256CBCHS512)
     let dataToEncrypt = plainJSONData.data(using: .utf8)!
     let payload = Payload(dataToEncrypt)
     let jwe = try? JWE(header: header, payload: payload, encrypter: encrypter)
     print(jwe!.compactSerializedString) 
    return String(format: "%@", jwe!.compactSerializedString)
    }

But receiving "Fatal error: Unexpectedly found nil while unwrapping an Optional value" as exception.

What may be the problem for this excpetion? Kindly suggest me the solution.

**Comment by daniel-mohemian** [comment]
Hi @VishnuV02,

when using direct encryption, you need to provide a shared symmetric key as encryption key. This shared symmetric key will be used as content encryption key for the symmetric content encryption algorithm. More details [here](https://tools.ietf.org/html/rfc7516#section-5.1).
