### ISSUE TITLE
Generate Random RSA Key

### ISSUE THREAD

**Issue by jplazcano87** [airsidemobile/JOSESwift#178]
hi, i'm doing an implementation in both Android and iOS, on Android i'm using Nimbus JOSE and calling function to generate a RSA Key from a random uuid 

```

    fun genRSAKeyPair(): RSAKey {
        return RSAKeyGenerator(2048) // Size of the key
                    .keyUse(KeyUse.ENCRYPTION)
            .keyID(UUID.randomUUID().toString())
            .generate()
    }

```
how can i generate a key like this, with this library?

thanks in advance

**Comment by daniel-mohemian** [comment]
Hi @jplazcano87,

JOSESwift does not deal with generating RSA keys. Checkout Apple's [Generating New Cryptographic Keys](https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/generating_new_cryptographic_keys) for information on how to generate asymmetric key pairs that you can use with JOSESwift.
