### ISSUE TITLE
Incorrect public key pemstring generated

### ISSUE THREAD

**Issue by yogendrakarekar** [airsidemobile/JOSESwift#180]
Following is my code in which I am trying to create a public key from modulus and exponent
var mod = "qzZwIDyV13LHZe9hXf282Us5MHSXq08+XKQPqoVG/2gY5g/6/HywzD5ZS2C18OaeXUEJmIoCeYXW3zE1N9YCf8B9XPqG9wRO2Hh7QB4UlZh2nUx43n7mPA9Xf8Ne7gLFfOu6OGo8w/SBfzFq1EojqGxtgiyBIG9FJll6VqE0wqE="
        var expo = "AQAB"
        var dict:[String:String] = ["kty":"RSA","n":mod,"e":expo]//"{"kty":"RSA","n":mod,"e":expo}"
        do{
            let jsondata = try JSONEncoder().encode(dict);
            let jwk = try! RSAPublicKey(data: jsondata)
            let publicKey: SecKey = try! jwk.converted(to: SecKey.self)
            var str = ""
            var error:Unmanaged<CFError>?
            if let cfdata = SecKeyCopyExternalRepresentation(publicKey, &error) {
               let data:Data = cfdata as Data
               str = data.base64EncodedString()
                print(str);
            }
        }catch{
            
        }

but it generates following pemstring which is wrong
MIGJAoGBAKs2cCA8lddyx2XvYV39vNlLOTB0l6tPPlykD6qFRv9oGOYP+vx8sMw+WUtgtfDmnl1BCZiKAnmF1t8xNTfWAn/AfVz6hvcETth4e0AeFJWYdp1MeN5+5jwPV3/DXu4CxXzrujhqPMP0gX8xatRKI6hsbYIsgSBvRSZZelahNMKhAgMBAAE=

as compared to pemstring generated by this site , please help
https://superdry.apphb.com/tools/online-rsa-key-converter

**Comment by daniel-mohemian** [comment]
Hi @yogendrakarekar 

Thanks for trying out JOSESwift.

`SecKeyCopyExternalRepresentation` returns data in the PKCS#1 format for an RSA key according to Apple's [documentation](https://developer.apple.com/documentation/security/1643698-seckeycopyexternalrepresentation).

This is part of iOSs SecKey API and not something we can influence. As long as you get a valid `SecKey` object, JOSESwift seems to do it's job. 

Just as a hint: The site you linked seems to use the X.509 SubjectPublicKeyInfo format which differs from PKCS#1.

If you have further concerns about functions provided by JOSESwift, feel free to open a new ticket.
