### ISSUE TITLE
Add GitHub actions instead of Travis

### ISSUE THREAD

**Issue by daniel-mohemian** [airsidemobile/JOSESwift#194]
Possible Travis alternative? Would get rid of an external dependency. cc @markus-mohemian.

**Comment by haeser** [comment]
Integration is pretty straight forward see [config](https://github.com/airsidemobile/JOSESwift/blob/task/github-actions/.github/workflows/config.yml)

Result looks like

<img width="290" alt="Screen Shot 2019-12-27 at 22 08 47" src="https://user-images.githubusercontent.com/24912807/71532811-7d269300-28f5-11ea-897f-395e8758b053.png">

and

<img width="998" alt="Screen Shot 2019-12-27 at 22 07 45" src="https://user-images.githubusercontent.com/24912807/71532779-55cfc600-28f5-11ea-9a4c-3353d28e5817.png">

> GitHub Actions usage is free for public repositories. [0]

Switching from Travis to Github actions should be a no brainer.

[0] [Billing for Github Actions](https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions)
