### ISSUE TITLE
Add Swift Package Manager Support

### ISSUE THREAD

**Issue by daniel-mohemian** [airsidemobile/JOSESwift#195]
SPM is supported for iOS [since Xcode 11](https://www.swiftbysundell.com/articles/managing-dependencies-using-the-swift-package-manager/). Would be cool to have JOSESwift also support it.

**Comment by Jonathan-Airside** [comment]
I'd also urge for adding `macos` and `tvos` support while performing this change, as SPM is used widely used by all platforms.
