### ISSUE TITLE
How to retrieve the private key while decrypting data

### ISSUE THREAD

**Issue by deepesh-vasthimal-cko** [airsidemobile/JOSESwift#218]
Hi, 

How do I get the private key from certificate ? when doing the decryption. 

`let privateKey: SecKey = /* ... */`

**Comment by daniel-mohemian** [comment]
Hi, please checkout Apples's [`Security.framework` docs](https://developer.apple.com/documentation/security/certificate_key_and_trust_services) for how to obtain references to existing keys.

**Comment by failynsedik** [comment]
Hello @deepesh-vasthimal-cko. Were you able to make it work? I'm facing the same difficulty even after checking the docs and implementing `SecKeyCreateWithData`.

**Comment by deepesh-vasthimal-cko** [comment]
@failynsedik 
if you are trying to get the private key from certificate then firstly thats wrong idea, the private key should be on the client side already to decrypt data. 

but if you want to use SecKeyCreateWithData with nsdata below is a good example. 

https://stackoverflow.com/questions/38097824/retrieve-seckey-from-nsdata

Thanks
