### ISSUE TITLE
Supporting ECDH Elliptic Curve Diffie–Hellman Key for Encrypter method 

### ISSUE THREAD

**Issue by deepesh-vasthimal-cko** [airsidemobile/JOSESwift#219]
Does Encrypter method support ECDH key ? ( Elliptic Curve Diffie–Hellman Key )

**Comment by daniel-mohemian** [comment]
No, unfortunately we do not support the ECDH key management mode variants at the moment. But we would happily review pull requests adding support as long as they make use of only native iOS cryptography (`Security.framework`, `CommonCrypto`, `CryptoKit.framework`).
