### ISSUE TITLE
Module 'JOSESwift' was not compiled with library evolution support; using it means binary compatibility for 'SnapKit' can't be guaranteed

### ISSUE THREAD

**Issue by deepesh-vasthimal-cko** [airsidemobile/JOSESwift#237]
Hi All, 

I have created a swift framework and adding the `joseswift` into my pod file as below, When i try to use and import Joseswift i get a warning about binary compatibility. Can anyone please help me fix this warning. 

<img width="972" alt="Screenshot 2020-10-23 at 03 31 15" src="https://user-images.githubusercontent.com/59569588/96949708-769a8500-14e0-11eb-8114-bac055122ff9.png">
<img width="533" alt="Screenshot 2020-10-23 at 03 32 13" src="https://user-images.githubusercontent.com/59569588/96949711-78644880-14e0-11eb-9648-6acda2e1908e.png">

**Comment by daniel-mohemian** [comment]
Hi @deepesh-vasthimal-cko! Yes we indeed don't have library evolution support enabled. 

Some background on this:

There's [an article](https://swift.org/blog/library-evolution/) on the Swift website that states:

> Library evolution support should only be used when a framework is going to be built and updated separately from its clients.

JOSESwift is always built together with its clients (via CocoaPods, Carthage, or SPM). We don't release pre-built binaries. Therefore, I believe, there's no need to enable library evolution support on our side.

Furthermore, the article states that:

> Frameworks that are always built and distributed together (...) should not be built with library evolution support.

This is exactly the case for JOSESwift.

---

If your framework requires the ABI stability that library evolution support guarantees you can always compile your dependencies (JOSESwift in this case) with the `BUILD_LIBRARY_FOR_DISTRIBUTION` [build setting](https://swift.org/blog/library-evolution/#enabling-library-evolution-support) enabled. The resulting binary should then have library evolution support enabled.

If you don't rely on ABI stability, [you can ignore this warning](https://forums.swift.org/t/risks-of-compiler-warning-module-was-not-compiled-with-library-evolution-support/33941/5).

**Comment by byohay** [comment]
@daniel-mohemian it is true that you don't need to enable library evolution support, however it would greatly help us if it would be guaranteed that the library compiles successfully with `BUILD_LIBRARY_FOR_DISTRIBUTION` enabled. Otherwise your clients (including us) would have to verify this themselves and diverge from your branch if it doesn't compile with the flag.
In practice this probably means creating tests would verify this.
The same was done in [GRDB](https://github.com/groue/GRDB.swift/pull/1037).

**Comment by dnlggr** [comment]
cc @nathan-mohemian who is leading this project now.
