### ISSUE TITLE
No Such Module : while generating a framework containing joseswift as pod

### ISSUE THREAD

**Issue by deepesh-vasthimal-cko** [airsidemobile/JOSESwift#238]
Hi All, 

I see a common discussed error on the internet about ``no such module found` `when creating a framework file contain a 3rd party dependency. In my case i am using `joseswift` inside my framework and then trying to create a framework. While doing so the archiving fails throwing a no such module 'JOSESwift' on the line where i have `import JOSESwift` statement. All help appreciated. 

<img width="1023" alt="Screenshot 2020-10-23 at 03 34 39" src="https://user-images.githubusercontent.com/59569588/96949973-16581300-14e1-11eb-9a15-32b6aba4dbc5.png">

**Comment by daniel-mohemian** [comment]
Hi @deepesh-vasthimal-cko! This looks like a generic build issue not related to JOSESwift. I'm going to close this issue since you can probably find better help elsewhere. Always make sure to properly link your binary to its dependencies and that the framework search paths are set correctly.
