### ISSUE TITLE
How to create JWK with all parameters

### ISSUE THREAD

**Issue by OndrejHRIC** [airsidemobile/JOSESwift#239]
Hi, first of all, great job. I was able to create JWK from RSA public key but my goal is to generate JWK that looks like this:
`{"kty":"RSA","e":"AQAB","n":"wJXHI...","d":"DkgNK...","p":"6M2y...","q":"08Yyu-EP...","dp":"JFQtE...","dq":"INakc...""qi":"aYfNB..."}`

Is there a way to do this? And if so, can you tell me how can I generate missing parameters **d, p, q, dp, dq and qi**?
Thanks 🙏

**Comment by daniel-mohemian** [comment]
Hi @OndrejHRIC! Looks like you are trying to create a JWK representing an RSA _private_ key (d, p , q, dp, dq, and qi [are parameters of RSA private keys](https://tools.ietf.org/html/rfc7518#section-6.3.2)). We don't currently support this. There is an open pull request that tries to implement exactly this, though. It is not mergeable at the moment but feel free to take a look. Maybe you can reuse some parts of that code or even take over the pull request. 👉 #231
