### ISSUE TITLE
JWS-/JWE 'jwk' header parameter should be a JSON dictionary

### ISSUE THREAD

**Issue by johanfylling** [airsidemobile/JOSESwift#241]
The JWS and JWE specifications dictate that the 'jwk' header parameter should be represented as a JWK (https://tools.ietf.org/html/rfc7515#section-4.1.3 & https://tools.ietf.org/html/rfc7516#section-4.1.5). The JWK representation is a JSON dictionary, and not a string, as currently implemented by JOSESwift.

**Comment by daniel-mohemian** [comment]
Linking #240 ⛓️

**Comment by johanfylling** [comment]
We are working against a release in a few weeks of the app using this library. We’d greatly appreciate an estimate for the time required to investigate and solve this issue, if you are able to provide one.
