### ISSUE TITLE
Add ECDH support for JWE  Key Management

### ISSUE THREAD

**Issue by MikaelRucinsky** [airsidemobile/JOSESwift#244]
Add EC support for JWE Key Management

ECDH-ES - Elliptic Curve Diffie-Hellman Ephemeral Static key agreement using Concat KDF
ECDH_ES_A128KW - ECDH-ES using Concat KDF and CEK wrapped with "A128KW"
ECDH_ES_A192KW - ECDH-ES using Concat KDF and CEK wrapped with "A192KW"
ECDH_ES_A256KW - ECDH-ES using Concat KDF and CEK wrapped with "A256KW"

**Comment by daniel-mohemian** [comment]
I'm closing this issue, everyone feel free to submit PRs or reopen #245.
