### ISSUE TITLE
Adding this as package

### ISSUE THREAD

**Issue by admc-development** [airsidemobile/JOSESwift#250]
This package always gets hung up when trying to add. 

Even this is not a proper declaration .package(url: "https://github.com/airsidemobile/JOSESwift.git") according to xcode.

**Comment by jamessmith-airside** [comment]
Hello fellow iOS developer! I was able to create a test project and import JOSESwift as a Swift Package. Can you share more information on how you are setting things up? Are you editing your package file manually, or are you accessing the Swift Packages tab from the Project File? Please see attached screenshots for my test setup. Please let us know if you are still unable to pull down the JOSESwift package. Have a great day, and stay swifty!

<img width="814" alt="Screen Shot 2021-01-08 at 8 57 17 AM" src="https://user-images.githubusercontent.com/56265480/104023845-40d87480-5190-11eb-9928-226bc2b2d3d8.png">

<img width="579" alt="Screen Shot 2021-01-08 at 8 57 41 AM" src="https://user-images.githubusercontent.com/56265480/104023897-4cc43680-5190-11eb-9f6f-df4f79e7bc0f.png">

<img width="452" alt="Screen Shot 2021-01-08 at 8 58 08 AM" src="https://user-images.githubusercontent.com/56265480/104023910-5352ae00-5190-11eb-872a-51088947f84b.png">

**Comment by admc-development** [comment]
Hey!

Thanks for the response. This error is when I add this package to a package you cannot use the package manager to do that only using .package() package.swift file which is where the issues lay.

**Comment by jamessmith-airside** [comment]
I see that our GitHub ReadMe is slightly incorrect in that is has this line for the SPM integration:

```
.package(url: "https://github.com/airsidemobile/JOSESwift.git")
```

I cannot know your dependency graph and how you want to pin versions, but if you try something like the following, do you still get the same error?

```
.package(url: "https://github.com/airsidemobile/JOSESwift.git", .exact("2.3.1"))
```

**Comment by daniel-mohemian** [comment]
I updated the readme with correct SPM installation instructions and verified that they work. I'm closing this issue. Let us know if you are still seeing issues and suspect it could me a mistake on our end @admc-development.
