### ISSUE TITLE
Signing using secure enclave keys

### ISSUE THREAD

**Issue by netgfx** [airsidemobile/JOSESwift#253]
Hello, I saw that that was some other issues #155 as well. Is there an example or part of documentation to see how this is implemented.

I'm mostly interested in JWS for this.

Thank you!

**Comment by daniel-mohemian** [comment]
Hi and welcome @netgfx! 👋 

Are you seeing issues using secure enclave keys for signing a JWS? If you could attach some example code we can take a look!

Generally, I'd recommend taking a look at [Apple's docs](https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/storing_keys_in_the_secure_enclave) on generating keys in the secure enclave. Note that JOSESwift does not handle key generation and storage. It expects you to do that according to your needs. It does not matter to JOSESwift _where_ a key is stored as long as it can be used for the requested cryptographic operation. Signing algorithms like ES256/ES384/ES512 should work just fine with elliptic-curve keys stored in the secure enclave. If you pass a key that is stored in the secure enclave, the singing operation will happen in the secure enclave as described [here](https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/storing_keys_in_the_secure_enclave).

I'm going to close this issue for now. If you see problems you suspect to be related to JOSESwift, please open a new GitHub issue with some example code to help us reproduce the issue. Thanks and let me know if you keep having problems!
