### ISSUE TITLE
Adding claim names

### ISSUE THREAD

**Issue by netgfx** [airsidemobile/JOSESwift#254]
Hello,

Is it possible to include claim names https://tools.ietf.org/html/rfc7519#section-4.1 like:
```
iss (issuer): Issuer of the JWT
sub (subject): Subject of the JWT (the user)
aud (audience): Recipient for which the JWT is intended
exp (expiration time): Time after which the JWT expires
nbf (not before time): Time before which the JWT must not be accepted for processing
iat (issued at time): Time at which the JWT was issued; can be used to determine age of the JWT
jti (JWT ID): Unique identifier; can be used to prevent the JWT from being replayed (allows a token to be used only once)
```
on the payload?
Is there a proposed way to do this? I see that that JWSHeader contains some exposed properties.

Thanks.

**Comment by daniel-mohemian** [comment]
Hi @netgfx, you can use anything that's `Data` as `Payload`. Just encode your claims to `Data` and your done.

``` swift
let payload = Payload("anything you want".data(using: utf8)!)
```

 If you're looking for a purpose built JWT library, it might make sense to check out what's available at [jwt.io](https://jwt.io) as JOSESwift is only aiming at providing underlying JOSE (JWS/JWE/JWT) groundwork.

**Comment by netgfx** [comment]
@daniel-mohemian I opened the issue because after following the ReadMe instructions and wiki the JWS payload was indeed identified but I got the following message.

![BE3AE83A-9836-4690-968A-E91837F4B93F](https://user-images.githubusercontent.com/864248/109516768-3dd37380-7ab1-11eb-945f-da4da3e457b3.jpeg)

**Comment by daniel-mohemian** [comment]
What is your payload? From the jwt.io error message it seems it's not valid JSON.

Keep in mind that signed JWTs are a special subset of valid JWSs. Every signed JWT is a JWS but not every JWS is a JWT. Nothing will stop you from creating JWTs using JSOESwift. But nothing will stop you from creating a JWS which is _not_ valid JWT either.

**Comment by netgfx** [comment]
The payload is this: `"{'iss':twig,'exp':1701012559.846624,'sub':Hello Project Twig,'aud':twig users,'iat':1614612559.846685,'is_root':true}"` which is a valid JSON (according to JSON validators) but it is still not accepted.

**Comment by daniel-mohemian** [comment]
JSON required strings to be in double quotes. If you get your payload to be a valid JSON, it'll work.

See: https://www.json.org/json-en.html

**Comment by netgfx** [comment]
I got it working, if it helps anyone I had to convert a dictionarty into a JSON string through the JSONEncoder.

```
let dic:Dictionary<String,String> = [
      "iss": iss,
      "exp": exp,
      "sub": sub,
      "aud": aud,
      "iat": iat,
      "is_root": "true"
 ]
```
            
 Then            

```
  private func jsonEncode(data:Dictionary<String,String>) -> String? {
        let encoder = JSONEncoder()
        if let jsonData = try? encoder.encode(data) {
            if let jsonString = String(data: jsonData, encoding: .utf8) {
                print(jsonString)
                return jsonString
            }
            else {
                return nil
            }
        }
        else {
            return nil
        }
    }
    ```

**Comment by daniel-mohemian** [comment]
Good to hear you got it to work. Just to be clear though, the payload can be any `Data`. As long as that `Data` contains valid JSON, the final JWS payload will be valid JSON.
