### ISSUE TITLE
Why make all the signature validation logic internal?

### ISSUE THREAD

**Issue by yspreen** [airsidemobile/JOSESwift#257]
I wanted to use this library to validate ES256 signatures, since all the cryptographic code is there. And there isn't many solutions. Sadly, I'll have to find another library because of the extensive use of `internal` in this one, for pretty much all ES256 code. The only exposed method requires my data to be in the JWSHeader and Payload format, which it isn't.

**Comment by daniel-mohemian** [comment]
Hi @yspreen, this library is intended for use with JOSE data types only. If your data is not in this format — sadly this isn't the right library for you.
