### ISSUE TITLE
Very strange issue calling base64URLEncodingString on an image Data

### ISSUE THREAD

**Issue by jsoneaday** [airsidemobile/JOSESwift#265]
Having a very strange issue in xcode and swiftui, where the file base64url encoding seems to happen but when I try and display the string in xcode I see a huge long blank. It also can be converted back into a data object but then fails to load as a UIImage. 

The image selection happens in a PhotoPicker controller. It selects an image and converts it into a jpegData object and sets it to the property selectedImageData. The raw data object can be loaded as a UIImage successfully. 

This data object is later converted using base64URLEncodingString, which is successful. However the string is a giant blank?

I've included a several screenshots on the bottom, but the last one if on the terminal showing the giant blank when using base64URLEncodedString. Again this image does load as a UIImage before encoding.

```
struct PhotoPicker: UIViewControllerRepresentable {
    @Binding private var selectedImageData: Data?
    
    init(selectedImageData: Binding<Data?>) {
        self._selectedImageData = selectedImageData
    }
    
    final class Coordinator: NSObject, UIImagePickerControllerDelegate, UINavigationControllerDelegate {
        private var parent: PhotoPicker
        init(parent: PhotoPicker) {
            self.parent = parent
        }
        
        func imagePickerController(_ controller: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey: Any]) {
            if let image = info[.editedImage] as? UIImage {
                self.parent.selectedImageData = image.jpegData(compressionQuality: 1)
            }
            controller.dismiss(animated: true)
        }
    }
    
    func makeCoordinator() -> Coordinator {
        return Coordinator(parent: self)
    }
    
    func makeUIViewController(context: UIViewControllerRepresentableContext<PhotoPicker>) -> UIImagePickerController {
        let controller = UIImagePickerController()
        controller.delegate = context.coordinator
        controller.allowsEditing = true
            
        return controller
    }
    
    func updateUIViewController(_ uiViewController: UIImagePickerController, context: UIViewControllerRepresentableContext<PhotoPicker>) { }
}
```

![image](https://user-images.githubusercontent.com/1474935/145579356-fe3d949f-21cf-4bf3-b642-fdf4fb94a3c5.png)
![image](https://user-images.githubusercontent.com/1474935/145579501-bde817cd-05c0-42b5-923b-51b786c407a4.png)
![image](https://user-images.githubusercontent.com/1474935/145580903-2e0e7587-8f9b-4c11-9286-c4a4916eb327.png)

**Comment by jamessmith-airside** [comment]
Hi, thanks for opening the issue. We have seen this behavior before with Xcode. What you are describing sounds like, to me, an Xcode limitation of printing extremely long strings to the console. A base64 encoded image could result in a massively long string. I have seen this when logging out network POSTs which contain a base64 encoded image in the body. The console logs will have a huge blank spot that I have to edit out in a text editor.

We will confirm the issue and look into it. If there is a problem with the code we will take a look.

Thanks!

**Comment by jsoneaday** [comment]
Thanks for responding. So the main issue is not the huge blank text. It's that once converted back into a data object it does not load into a UIImage. I've tried it with several images now and same issue. The blank is just an odd inconvenience.

**Comment by jsoneaday** [comment]
Yep my issue switched to using Data(base64URLEncoded: avatarBase64Url ?? "")  and it worked.

Sorry for wasting your time. Thank you for the awesome library!
