### ISSUE TITLE
is A128CBC-HS256 not available currently?

### ISSUE THREAD

**Issue by sil-ios** [airsidemobile/JOSESwift#272]
I found the closed issue (#82) in 2019 for using A128CBC-HS256.

But I think A128CBC-HS256 is deprecated now.

Is there any way to use A128CBC-HS256 with JOSESwift?

**Comment by haeser** [comment]
Hey, it is available since https://github.com/airsidemobile/JOSESwift/releases/tag/1.8.0 was released. You can use it like any other supported JWE algorithm.
