### ISSUE TITLE
Custom Header Parameter Names

### ISSUE THREAD

**Issue by tobihagemann** [airsidemobile/JOSESwift#277]
Currently, the header parameters are strictly defined and I couldn't find a way to extend them with custom ones.

In `JOSEHeader` and its implementations, `parameters` can only be accessed internally so that you can't define custom parameters outside of this library.

Would it make sense to make `parameters` public? Or any other idea how custom header parameter names can be accomplished?

**Comment by CyberMew** [comment]
+1 to this. At least let us extend the “fixed header”`parameters` ourselves via an extension or expose it or something. Is the current behaviour strictly by design?

**Comment by ollikas** [comment]
+1 for that. Since RFC7516 clearly states the [Private Header Names](https://www.rfc-editor.org/rfc/rfc7516#section-4.3), library should support both writing and reading them, as one of the purposes of the Private Headers are to validate their content before proceeding with the decryption.

**Comment by tobihagemann** [comment]
Ah, very nice, there is already a PR #282 by @taavi224 for this. To be honest, there are already multiple PRs that would just need a merge so that this library gets better and better but I'm not sure what the maintainers are up to. I know that I can maintain my own fork but it would be great if these changes could be merged upstream.

**Comment by haeser** [comment]
resolved via #312
