### ISSUE TITLE
Project Maintenance

### ISSUE THREAD

**Issue by tobihagemann** [airsidemobile/JOSESwift#284]
Hello Airside Mobile team,

I'm curious about the state of this project. It doesn't seem to be maintained anymore, especially after the departure of @daniel-mohemian (who is now a "ghost"). Are there any plans for you to review the issues and PRs?

I know that you aren't obligated to maintain this project and I'm already very grateful for your open-source contributions. I guess I just wanted to hear from you because I'm not sure if my energy is well spent to provide PRs and ask questions in the issues. I'm aware that I can just work on my fork and be done with it but in the spirit of open source, I think it's just fair to "give back". What do you think?

Notifying the project authors, maintainers, and reviewers from the README: @carol-mohemian @gigi-mohemian @haeser @michael-mohemian

**Comment by spheroid** [comment]
I'm also wondering what the state of this project is. It provides much value to us and we're really grateful that it exists in the first place, but the lack of some features (that are already addressed in the current PR's!) is a bit problematic. I also understand that I'm not in position to demand anything from you, but I'm just wondering if the current maintainers do not have the resources to keep managing the project if they would be willing to let any volunteers step in?

**Comment by daniel-moh** [comment]
Hey everyone, 👋

Thanks for opening this issue—it's a very valid point and it's good that you raised it. Indeed, we haven't been able to commit resources to this project over the last couple of years and this—unfortunately—wasn't communicated well to the community here.

**However, the good news is that that going forward we will be able to dedicate some time to the project again.**

In the next couple of weeks, I will be going over the open PRs and open issues to get an overview of the current state of the project. If anyone has any input for me regarding prioritization of open PRs/issues, please let me know here.

*Just to set the expectations right:* The project will be maintained again, our resources are still constrained, though. The plan is to prioritize reviewing the open PRs and sorting through the open issues. After that we'll make sure the project is at least passively maintained by us, meaning we'll review and merge PRs if they fit the project and we will give guidance and participate in discussions around new features.

Thanks for your understanding and sorry for the lack of communication recently. Going forward I'll be the lead maintainer of the project and you can ping me anytime with questions or feedback.

**Comment by tobihagemann** [comment]
Thank you, @daniel-moh, I'm very happy to hear the good news! 🎉

I can only speak for our own project but we've made use of these 3 PRs:

- https://github.com/airsidemobile/JOSESwift/pull/268
- https://github.com/airsidemobile/JOSESwift/pull/278
- https://github.com/airsidemobile/JOSESwift/pull/282

I guess "more support" for algorithms doesn't hurt but the second PR would require an increased minimum iOS target, which should be taken into consideration. And I don't know if the last PR requires more discussion but custom header parameter names was requested by other users as well.

**Comment by daniel-moh** [comment]
Closing this issue. Please see #305 for the latest updates on our maintenance role and the concrete next steps we will take to revive this project.

Thanks everyone!
