### ISSUE TITLE
Clarification on Project Maintenance

### ISSUE THREAD

**Issue by YesidMarin** [airsidemobile/JOSESwift#305]
There have been no updates for 3 years and there are several open issues without resolution. This is a good project, and I hope it doesn't end up forgotten. I have a couple of issues in my implementations, but I won't mention them as they are addressed in other discussions. Will there be an update soon?

**Comment by ferencIOS** [comment]
Hello,

I have recently forked the repository here: [ferencIOS/JOSESwift](https://github.com/ferencIOS/JOSESwift) and plan to take on a maintenance role to keep this project active. I encourage everyone with open pull requests on this original repository to repost them to the new repository, where they will be reviewed and merged appropriately.

Should anyone from the original team at www.airsidemobile.com or any other contributors have concerns or disagree with this approach, please let me know. I am open to closing the repository if that is the preferred course of action. However, my primary goal is to ensure that this project continues to grow and serve the community.

Thank you for your contributions, and I look forward to your continued support.

( @tobihagemann @mohemian-92817281 @xavierLowmiller @haeser @mschwaig @Torsph )

**Comment by daniel-moh** [comment]
👋 Hi everyone,

thanks so much for your patience and for keeping the conversation alive around JOSESwift. Special thanks to @ferencIOS for offering to stepping up and taking a more active role as maintainer during our, unfortunately very long, quiet period.

A lot has happened behind the scenes. [Airside was acquired](https://onfido.com/blog/entrust-and-onfido-a-new-era-of-identity-centric-security-is-here/), leading to some big changes that unfortunately shifted our attention away from JOSESwift. After hearing your concerns, we discussed things with Airside's management and are happy to announce that we secured a solid commitment to invest in reviving this project. It’s great to see how much you all care, and we’re excited to jump back in!

**🚀  Here’s the game plan and our concrete next steps:**

- By the end of this week, we’re aiming to sort out all the straightforward, easy to review PRs (e.g., [#294](https://github.com/airsidemobile/JOSESwift/pull/294), [#303](https://github.com/airsidemobile/JOSESwift/pull/303), [#295](https://github.com/airsidemobile/JOSESwift/pull/295)).
- Over the next two weeks, we’ll tackle the rest of the open PRs (e.g., [#269](https://github.com/airsidemobile/JOSESwift/pull/268), [#278](https://github.com/airsidemobile/JOSESwift/pull/278), [#282](https://github.com/airsidemobile/JOSESwift/pull/282)).
- We’ll also work with the community and look into whether it makes sense to pull any changes that have made it into  existing forks back into the main repo. Please feel free to give us pointer to where we should look for here.

I’ll keep this thread updated to keep everyone in the loop as we make progress. I'm here along with @haeser and others from our team, ready to dive into discussions and help out. If anyone’s keen to get more involved, especially with reviewing PRs, we’d love the help!

Let us know your thoughts, and once again, a huge thanks to everyone for pushing us to get back to this. 

Here’s to JOSESwift’s next chapter! 🍻

**Comment by daniel-moh** [comment]
📣 **Update**

We've opened https://github.com/airsidemobile/JOSESwift/pull/310 which will address most of the trivial PRs that were opened recently. For simplicity I closed those other PRs in favor of this one.

Open for feedback!

**Comment by daniel-moh** [comment]
We just released https://github.com/airsidemobile/JOSESwift/releases/tag/3.0.0 including  most of the recent contributions, check it out! I'll close this issue, if there's any questions or concerns, let me know!
