### ISSUE TITLE
Restructure headers (if possible)

### ISSUE THREAD

**Issue by carol-mohemian** [airsidemobile/JOSESwift#60]
The headers are still a bit weird especially with the `init(parameters:, headerData:)` initializer (that the data has to be passed is strange). Maybe we can come up with a cleaner and simpler solution for JOSE/JWS/JWE header.

Looks like custom header parameters are not possible as well at the moment. 

NOTE: The `headerData` is necessary because the parameters dictionary might not be in the same order and therefore the signature could be invalid.

**Comment by daniel-mohemian** [comment]
Moving to a note in the [project board](https://github.com/airsidemobile/JOSESwift/projects/1).
