### ISSUE TITLE
Setup SonarCloud/SwiftLint on Travis

### ISSUE THREAD

**Issue by carol-mohemian** [airsidemobile/JOSESwift#71]
Setup SonarCloud and/or SwiftLint on Travis for static code analysis.

**Comment by carol-mohemian** [comment]
https://docs.travis-ci.com/user/sonarcloud/

**Comment by daniel-mohemian** [comment]
Moving to a note on the [project board](https://github.com/airsidemobile/JOSESwift/projects/1).
