### ISSUE TITLE
Improve test suite for RSASigner/Verifier, RSAEncrypter/Decrypter and AESEncrypter/Decrypter

### ISSUE THREAD

**Issue by gigi-mohemian** [airsidemobile/JOSESwift#77]

**Comment by gigi-mohemian** [comment]
@daniel-mohemian I'd be happy to discuss this issue with you in more detail, since I think you have the best overview of what's missing and how the test suite could be improved.

**Comment by daniel-mohemian** [comment]
I'll close this for now.
